### ISSUE TITLE
Enabling issue tracking on your fork of WinMTR

### ISSUE THREAD

**Issue by unforgettableid** [smilepleeeaz/My_Repo#1]
Hi!

I wonder if you could please do the following?

A)  Visit https://github.com/smilepleeeaz/WinMTR/settings

B)  Add a checkmark to the "Issues" checkbox, so as to enable issue tracking on your fork.

Thanks!

**Comment by smilepleeeaz** [comment]
Done.

**Comment by unforgettableid** [comment]
Thanks :)

Closing.
